import type { DashboardData } from '@/lib/types';
import { currentMonth } from '@/lib/format';
export function seedData(): DashboardData {
  const month = currentMonth();
  const names = [
    'Aarav Sharma',
    'Priya Nair',
    'Rohan Mehta',
    'Ananya Iyer',
    'Vikram Singh',
    'Sneha Reddy',
    'Arjun Patel',
    'Ishita Das',
    'Aditya Rao',
    'Meera Joshi',
    'Karan Malhotra',
    'Diya Kapoor',
  ];
  const tenants = names.map((name, i) => ({
    id: `tenant-${i + 1}`,
    name,
    email: `${name.split(' ')[0].toLowerCase()}@example.com`,
    phone: `+91980000${String(i + 1).padStart(4, '0')}`,
    room: `${i < 6 ? 'A' : 'B'}-${101 + (Math.floor(i / 2) % 3)}`,
    bed: i % 2 ? '02' : '01',
    moveIn: `2026-0${1 + (i % 6)}-01`,
    rent: i % 3 === 0 ? 9500 : 8500,
    deposit: 17000,
    documents: [],
  }));
  return {
    property: {
      id: 'property-demo',
      name: 'Maple House',
      address: '12, 5th Cross, Koramangala, Bengaluru',
      rooms: 10,
      beds: 20,
      food: true,
      code: 'MAPLE24',
      notifications: true,
    },
    tenants,
    rents: tenants.flatMap((t, i) => [
      {
        id: `rent-${i + 1}`,
        tenantId: t.id,
        month,
        amount: t.rent,
        dueDate: `${month}-05`,
        paidAt: i < 8 ? `${month}-03T10:00:00Z` : null,
      },
      {
        id: `rent-old-${i + 1}`,
        tenantId: t.id,
        month: new Date(new Date().getFullYear(), new Date().getMonth() - 1, 15)
          .toISOString()
          .slice(0, 7),
        amount: t.rent,
        dueDate: new Date(new Date().getFullYear(), new Date().getMonth() - 1, 5, 12).toISOString(),
        paidAt: new Date(new Date().getFullYear(), new Date().getMonth() - 1, 3, 12).toISOString(),
      },
    ]),
    complaints: [
      {
        id: 'complaint-1',
        tenantId: 'tenant-3',
        title: 'Water purifier needs a check',
        description:
          'The water purifier on the first floor is not dispensing water. Could someone take a look?',
        category: 'Maintenance',
        priority: 'High',
        status: 'Open',
        createdAt: `${month}-19T09:20:00Z`,
        photo: null,
        notes: [],
      },
      {
        id: 'complaint-2',
        tenantId: 'tenant-6',
        title: 'Wi-Fi is slow in Block A',
        description: 'The connection drops frequently in the evenings.',
        category: 'Maintenance',
        priority: 'Medium',
        status: 'In progress',
        createdAt: `${month}-18T14:00:00Z`,
        photo: null,
        notes: [
          {
            text: 'Technician scheduled for tomorrow morning.',
            at: `${month}-19T10:00:00Z`,
            status: 'In progress',
          },
        ],
      },
      {
        id: 'complaint-3',
        tenantId: 'tenant-1',
        title: 'Request for less spicy dinner',
        description: 'Could we have a mild option for dinner?',
        category: 'Food',
        priority: 'Low',
        status: 'Open',
        createdAt: `${month}-18T08:00:00Z`,
        photo: null,
        notes: [],
      },
      {
        id: 'complaint-4',
        tenantId: 'tenant-9',
        title: 'Common area cleaning',
        description: 'Please arrange cleaning of the second-floor common area.',
        category: 'Housekeeping',
        priority: 'Medium',
        status: 'Resolved',
        createdAt: `${month}-16T08:00:00Z`,
        photo: null,
        notes: [
          { text: 'Deep cleaning completed.', at: `${month}-17T10:00:00Z`, status: 'Resolved' },
        ],
      },
    ],
    announcements: [
      {
        id: 'announcement-1',
        title: 'A little refresh for our common spaces',
        body: 'The lounge will be getting a fresh coat of paint this Saturday, 10 AM–4 PM. Please use the study room during this time. Thank you for your patience!',
        audience: 'All tenants',
        createdAt: `${month}-19T10:00:00Z`,
        reads: [
          'tenant-1',
          'tenant-2',
          'tenant-3',
          'tenant-5',
          'tenant-6',
          'tenant-7',
          'tenant-9',
          'tenant-11',
        ],
        image: null,
      },
      {
        id: 'announcement-2',
        title: 'Your feedback is on the menu',
        body: 'We’re updating next month’s mess menu. Share your favourite dishes with us by raising a food request — we’d love to hear from you.',
        audience: 'All tenants',
        createdAt: `${month}-17T10:00:00Z`,
        reads: ['tenant-1', 'tenant-4', 'tenant-8'],
        image: null,
      },
    ],
    menu: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'].map(
      (day, i) => ({
        day,
        breakfast: [
          'Idli, sambar & chutney',
          'Poha & fruit',
          'Dosa & chutney',
          'Aloo paratha & curd',
          'Upma & banana',
          'Puri & aloo sabzi',
          'Masala dosa & chutney',
        ][i],
        lunch: [
          'Roti, dal & jeera rice',
          'Rajma, rice & salad',
          'Roti, mixed veg & dal',
          'Chole, rice & raita',
          'Sambar rice & poriyal',
          'Veg pulao & raita',
          'Special veg thali',
        ][i],
        dinner: [
          'Roti, paneer & salad',
          'Roti, dal tadka & rice',
          'Veg biryani & raita',
          'Roti, aloo gobi & dal',
          'Roti, palak paneer',
          'Roti, chana masala',
          'Fried rice & manchurian',
        ][i],
      }),
    ),
    notifications: [],
    revision: 0,
  };
}
